import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import styled from "styled-components";
import { QuebraCabeca } from "../src/components/QuebraCabeca";
import { Controlador } from "../src/components/QuebraCabeca/controlador";

const Title = styled.h1`
  font-size: 50px;
  color: ${({ theme }) => theme.colors.primary};
`;

const QuebraCabecaJogo: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;

  if (id === undefined) {
    throw new Error("Theme not found");
  }

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Title>{id}</Title> */}

      <QuebraCabeca id={id.toString()} />
    </>
  );
};

export default QuebraCabecaJogo;
